{ lib, pkgs, ... }:
{
  imports = [ ./hardware-configuration.nix ./disk-config.nix ];
  networking.hostName = "nuc";
  networking.networkmanager.enable = true;
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  # Desktop retained; server must recover unattended after power loss.
  systemd.sleep.settings.Sleep = {
    AllowSuspend = "no";
    AllowHibernation = "no";
    AllowHybridSleep = "no";
    AllowSuspendThenHibernate = "no";
  };
  users.groups.liou.gid = 1000;
  users.users.liou = {
    uid = 1000;
    group = "liou";
    extraGroups = [ "users" ];
    initialPassword = lib.mkForce null;
    # Set locally with passwd after restoring; never ship a shared password.
    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJn4d0pLw296RyNQ+4mGUZ4Obja72o2SjG8E/CNhm8QD"
    ];
  };
  # Temporary migration root key removed after user-confirmed business recovery.
  # Preserve the separately managed shared administrator key policy.
  home-manager.users.liou.imports = [ ../../../home-manager/nix_modules/nuc-tunnel.nix ];
  # Server boot/activation must not wait on optional npm tooling or registry access.
  # Keep the shared workstation policy unchanged; tools can be installed manually.
  home-manager.users.liou.home.activation.ensureDshLatest = lib.mkForce {
    after = [ "linkGeneration" ];
    before = [ ];
    data = ''echo "NUC: skipping optional npm tool updates during activation"'';
  };
  environment.systemPackages = with pkgs; [ python3 rsync zstd ];
  # Create the parent explicitly before nested root-run tmpfiles rules do so.
  # A root-owned .config blocks first-boot Home Manager link generation.
  systemd.tmpfiles.rules = [ "d /home/liou/.config 0700 liou liou -" ];
  boot.kernel.sysctl."net.ipv4.ip_unprivileged_port_start" = 80;
  networking.firewall = {
    allowedTCPPorts = [ 80 443 5008 5009 ];
    allowedUDPPorts = [ 443 ];
    extraCommands = ''
      iptables -w -A nixos-fw -s 192.168.1.0/24 -p tcp --dport 5006 -j nixos-fw-accept
      iptables -w -A nixos-fw -s 192.168.1.0/24 -p tcp --dport 22000 -j nixos-fw-accept
      iptables -w -A nixos-fw -s 192.168.1.0/24 -p udp --dport 22000 -j nixos-fw-accept
      iptables -w -A nixos-fw -s 192.168.1.0/24 -p udp --dport 21027 -j nixos-fw-accept
    '';
  };
  # Existing media filesystems: mount only, NEVER include them in disko.
  fileSystems."/media/liou/Art" = {
    device = "/dev/disk/by-uuid/5F82-B190";
    fsType = "exfat";
    options = [ "nofail" "x-systemd.automount" "x-systemd.device-timeout=15s" "uid=1000" "gid=1000" "fmask=0022" "dmask=0022" ];
  };
  fileSystems."/media/liou/project" = {
    device = "/dev/disk/by-uuid/8bce6197-7281-40a0-84ec-e31c3d313877";
    fsType = "ext4";
    options = [ "nofail" "x-systemd.automount" "x-systemd.device-timeout=15s" ];
  };
  # Compose units remain generated by deploy/bootstrap; enable only after restore.
  # Existing generated preflight validates required_mounts before any container starts.
}
