services:
  caddy:
    depends_on:
      - dufs-readonly
      - tag-server-readonly

  dufs-readonly:
    image: ${DUFS_IMAGE}
    restart: unless-stopped
    command:
      - /data
      - --allow-symlink
      - --allow-archive
    networks:
      - app

  tag-server-readonly:
    image: ${TAG_SERVER_IMAGE}
    restart: unless-stopped
    networks:
      - app
