name: ${COMPOSE_PROJECT_NAME:-dufs-plus}

services:
  caddy:
    image: ${CADDY_IMAGE}
    restart: unless-stopped
    depends_on:
      - dufs
      - tag-server
    networks:
      - app

  dufs:
    image: ${DUFS_IMAGE}
    restart: unless-stopped
    command:
      - /data
      - --allow-all
      - --allow-symlink
    networks:
      - app

  tag-server:
    image: ${TAG_SERVER_IMAGE}
    restart: unless-stopped
    networks:
      - app

networks:
  app:
    driver: bridge
    ipam:
      config:
        - subnet: ${CONTAINER_SUBNET}
